### ISSUE TITLE
NUnit3TestAdapter dependency

### ISSUE THREAD

**Issue by bhorn** [Embarcadero/IB.NETDataProvider#16]
Embarcadero.Data.InterBaseClient.csproj has a dependency on NUnit3TestAdapter. Is this required? It seems a bit odd for a database driver to link to any unit test library.

**Comment by jeffovercash** [comment]
No, I'll remove it in the next release.  Surprisingly I would have expected that to have crept in on the .net 60 stuff, but it was in the net 4.52 group.

**Comment by jeffovercash** [comment]
Fixed in the 7.13.6 release
