### ISSUE TITLE
'SEP password' connection string option is inconsistent with wiki documentation

### ISSUE THREAD

**Issue by skermajo** [Embarcadero/IB.NETDataProvider#2]
There is a whitespace difference between what is documented in the wiki and what is in code. Wiki says `SEPPassword` however in code it is `SEP password` (`ConnectionString.cs`). Attempting to use the documented `SEPPassword` does not work. `SEP password` (with the extra whitespace) is working though.

See: http://docwiki.embarcadero.com/InterBase/2020/en/Setting_the_System_Encryption_Password_(SEP)

**Comment by jeffovercash** [comment]
Fixed.  I have not done a rebuild of the installer at this time so still broken in the installer.  I have added to the releases the documentation as its own standalone piece.  Thanks for the catch, I probably "cleaned" it up when I was pulling from the code and pasted it into that table.

**Comment by jeffovercash** [comment]
Ok slight misstatement.  The first column represents the property name in the IBConnectionString.  So SEPPassword is correct in that first column.  The second column represents the potential key names you can use if writing the connectionstring by hand.  In most cases the property name was always included as either the default key name or an alternative so I didn't put it again.  In this case SEPPassword (and above it instanceName) were not included as alternatives, and the defaults were "SEP password" and "Instance Name"

I updated the middle column to include all keys that can be used for that property and the default is in bold. I also added a little more language at the top to clarify the first column's semantics vs the second.
