### ISSUE TITLE
Support for EFCore 6.0

### ISSUE THREAD

**Issue by ulrich-berkmueller** [Embarcadero/IB.NETDataProvider#7]
Hello,

first up, thank you for providing an Entity Framework Core provider for Interbase.

Due to the fact that there have only been some commits in April and May and only EF Core 3.1 is mentioned in the docs:
**Was this a one time effort or will this project be actively maintained?**

Thinking ahead, [EF Core 3.1 LTS will only be supported until 2022-12-03](https://docs.microsoft.com/en-us/ef/core/what-is-new/) and there is already a stable version of EF Core 6.0 with LTS support.
Are there any plans to support Entity Framework Core 6.0 (and/or 5.0 as and intermediate step) within the next _n_ quarter(s) / the next year?

**Comment by jeffovercash** [comment]
yes, it is being developed, unfortunately, I came down with a severe case
of covid that has had me hospitalized for the past 3 months including 19
days in a coma.  I am in rehab learning to walk again. Once out I have
documentation to finish for change view support which is already coded and
demo done, but I got sick before updating the installers and docs.  EF6 is
high on the list once I have access to my equipment again.

Unfortunately, I can not give any estimate cause even out of rehab I won't
be working full days for a bit.

**Comment by ulrich-berkmueller** [comment]
Oh dear, that sounds terrible. So it's totally clear why the project got stuck.
I wish you the very best, that you will be completely healthy again soon. 

Despite all that, it's good to know that it wasn't a one-time effort and an official and maintained EFCore provider is there/will be present over time.

**Comment by DavyLGinkoia** [comment]
Hello @jeffovercash ,

I would like to know if this development have been stop. If non do you have estimate date for this.
Thanks

**Comment by jeffovercash** [comment]
EFCore 6.0 (and 7.0) are still planned to be supported.  Are there particular features from 5.0, 6.0 or 7.0 you are looking for?

Please note that EFCore is not EF6.0 (well 6.4 now).  EF6 is no longer in development by MS and is only going to get security updates from here on out.  For this reason, we are going to concentrate on the EFCore side of things.

**Comment by DavyLGinkoia** [comment]
@jeffovercash, thanks for your feedback

Here are some implementations we would need

With our version of Interbase XE the generated queries are not well interpreted with the DB engine. For example "AS" problems

A desired functionality would be taking into account of 
ValueGeneratedOnAdd().HasDefaultValueSql which does not seem to work.

We are in the writing of micro service on this basis and that's why the EFCore 6.0 support seems to us very important because the .NET Core Framework 3.1 will not be maintained any more in December 13, 2022 and that's why we wish to use .NET 6.0

**Comment by jeffovercash** [comment]
The 7.13.6 release updates the EFCore code to EFCore 6.0 (based on the Fb 9.x code doing the same thing).
