### ISSUE TITLE
Unable to cast object of type IBCommand

### ISSUE THREAD

**Issue by tramesh2009** [Embarcadero/IB.NETDataProvider#9]
Hi,

The following error is showing while fill the data in dataset from database. This issue happened only hosting environment not development environment.

Unable to cast object of type 'InterBaseSql.Data.InterBaseClient.IBCommand' to type 'System.Data.OleDb.OleDbCommand'.

Do i need install any dependencies?

Please help to resolve this issue

**Comment by jeffovercash** [comment]
You need .NET installed on the machine, the InterBase client library, and the ADO.NET client all installed on the destination machine.
